<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdmistrationReservationAeroportController::Annulation' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController::FicheDeMission' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController::Modification' => ['privates', '.service_locator.6IyCi5X', 'get_ServiceLocator_6IyCi5XService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController::ModifierReservation' => ['privates', '.service_locator.y7TRabD', 'get_ServiceLocator_Y7TRabDService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController::pdf' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\HomeController::Administration' => ['privates', '.service_locator.a55Q.Tk', 'get_ServiceLocator_A55Q_TkService.php', true],
    'App\\Controller\\HomeController::horairesdynamique' => ['privates', '.service_locator.a55Q.Tk', 'get_ServiceLocator_A55Q_TkService.php', true],
    'App\\Controller\\HomeController::reservation' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\HomeController::reservationAller' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController:Annulation' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController:FicheDeMission' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController:Modification' => ['privates', '.service_locator.6IyCi5X', 'get_ServiceLocator_6IyCi5XService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController:ModifierReservation' => ['privates', '.service_locator.y7TRabD', 'get_ServiceLocator_Y7TRabDService.php', true],
    'App\\Controller\\AdmistrationReservationAeroportController:pdf' => ['privates', '.service_locator.1ALwcuH', 'get_ServiceLocator_1ALwcuHService.php', true],
    'App\\Controller\\HomeController:Administration' => ['privates', '.service_locator.a55Q.Tk', 'get_ServiceLocator_A55Q_TkService.php', true],
    'App\\Controller\\HomeController:horairesdynamique' => ['privates', '.service_locator.a55Q.Tk', 'get_ServiceLocator_A55Q_TkService.php', true],
    'App\\Controller\\HomeController:reservation' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\HomeController:reservationAller' => ['privates', '.service_locator.Z_.o95M', 'get_ServiceLocator_Z_O95MService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
