<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSMfxNGg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSMfxNGg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSMfxNGg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSMfxNGg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSMfxNGg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SMfxNGg',
    'container.build_id' => 'e66c8835',
    'container.build_time' => 1555079488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSMfxNGg');
